language: bash

services:
  - docker

env:
  global:
    # change the registry name and username/password to yourself's.
    #- DOCKER_HUB=succw
    - ALI_REGISTRY=registry.cn-hangzhou.aliyuncs.com/belonace

before_script:
  #- echo "$ALI_REGISTRY"
  - echo "$ALI_PASSWORD" | docker login registry.cn-hangzhou.aliyuncs.com/belonace -u "$ALI_USERNAME" --password-stdin
 
script:
  - echo "start pull and retag and push"
  - |
    for image in $(cat img-list.txt)
    do
      image_name=${image##*/}
      image_name=${image_name%@*}
      docker pull $image
      echo $ALI_REGISTRY
      docker tag $image $ALI_REGISTRY/$image_name
      docker push $ALI_REGISTRY/$image_name
    done
